# Givens Rotations

Step-by-step example of incremental QR factorization as outlined in *iSAM: Incremental Smoothing and Mapping* by Kaess et al.

In [3]:
import numpy as np

Create a random matrix $\mathbf{A}$ to factorize

In [4]:
#A = np.random.rand(4,4)
#A = np.matrix([[1,2,3,4],[5,-6,-7,8],[-9,-10,-1,11],[12,-13,-14,-15]])
A = np.matrix([[1,2,3], [4,-5,-6], [-7, 8, 9]])
print(A)

[[ 1  2  3]
 [ 4 -5 -6]
 [-7  8  9]]


In [18]:
def givensStep(A):
    '''
    performs a single givens rotation, and outputs result
    '''
    # Initialize givens rotation matrix
    G = np.eye(len(A))
    getout = False
    for k in range(len(A)):
        for i in reversed(range(k+1, len(A))):
            print(A[i,k])
            if np.abs(A[i,k]) >= 1e-10:
                alpha = A[k,k]
                beta = A[i,k]
                r = np.sqrt(alpha**2 + beta**2)
                print("alpha = " + str(alpha) + ", beta = " + str(beta) + ", r = " + str(r))
                # Compute Givens Rotation Matrix according to criteria:
                c = alpha * (1/r) 
                s = beta * (1/r)
                # Assing the values to the matrix:
                G[k,k] = c
                G[i,k] = -s
                G[k,i] = s
                G[i,i] = c
                print("Givens Rotation")
                print(G)
                return(G)
                getout = True
                break
        if getout:
            break
            
def cleanMat(A):
    '''
    set small values to zero
    '''
    for i in range(len(A)):
        for j in range(len(A)):
            if np.abs(A[i,j]) <= 1e-7:
                A[i,j] = 0
    return A
        

In [33]:
G = givensStep(A)

-7
alpha = 1, beta = -7, r = 7.0710678118654755
Givens Rotation
[[ 0.14142136  0.         -0.98994949]
 [ 0.          1.          0.        ]
 [ 0.98994949  0.          0.14142136]]


In [34]:
A2 = cleanMat(G*A)
print(A2)

[[ 7.07106781 -7.63675324 -8.48528137]
 [ 4.         -5.         -6.        ]
 [ 0.          3.11126984  4.24264069]]


In [35]:
G2 = givensStep(A2)

0.0
4.0
alpha = 7.0710678118654755, beta = 4.0, r = 8.12403840463596
Givens Rotation
[[ 0.87038828  0.49236596  0.        ]
 [-0.49236596  0.87038828  0.        ]
 [ 0.          0.          1.        ]]


In [36]:
A3 = cleanMat(G2*A2)
print(A3)

[[  8.1240384   -9.10877033 -10.33968524]
 [  0.          -0.59186403  -1.04446594]
 [  0.           3.11126984   4.24264069]]


In [37]:
G3 = givensStep(A3)

0.0
0.0
3.111269837220809
alpha = -0.5918640302493732, beta = 3.111269837220809, r = 3.167065365650515
Givens Rotation
[[ 1.          0.          0.        ]
 [ 0.         -0.1868809   0.98238258]
 [ 0.         -0.98238258 -0.1868809 ]]


In [40]:
A4 = cleanMat(G3*A3)
print(A4)

[[  8.1240384   -9.10877033 -10.33968524]
 [  0.           3.16706537   4.36308703]
 [  0.           0.           0.23319662]]


After four iterations, the $\mathbf{R}$ factor is obtained. The orthogonal matrix $\mathbf{Q}$ is obtained by multiplying the obtained Givens rotations:

In [49]:
Q = G3.transpose()*G2.transpose()*G.transpose()
print(Q)

[[ 0.12309149 -0.          0.        ]
 [ 0.         -0.16265895 -0.        ]
 [-0.          0.         -0.02642895]]


... not quite right. 